# xnodes: Exchange nodes framework
#         Simplistic event framework which enables unrelated nodes to exchange information, alter each other states and
#         provides the possibility to undo made changes.
#
# Author: Ralph Neumann
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, see <https://www.gnu.org/licenses/>.

name: Release Poetry Package

on:
  push:
    tags:
      - "v*"

jobs:
  Poetry-Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
          python_version: "3.10"
          poetry_install_options: "--sync --without dev"
          build_format: "wheel"
