# xnodes: Exchange nodes framework
#         Simplistic event framework which enables unrelated nodes to exchange information, alter each other states and
#         provides the possibility to undo made changes.
#
# Author: Ralph Neumann
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, see <https://www.gnu.org/licenses/>.

name: Pylint

on: [ pull_request ]

jobs:
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev
      - name: Analysing the code with pylint
        run: |
          poetry run pylint --rcfile=.pylintrc xnodes tests
